export const LapProduct = [
  {
    Name: "ASUS Vivobook 15",
    Company: "ASUS",
    image: "asus.jpg",
    Specification: "Intel Core i3 11th Gen (8 GB/256 GB SSD/Windows 11)",
    Price: 29990,
  },
  {
    Name: "ASUS Vivobook S14",
    Company: "ASUS",
    image: "asus.jpg",
    Specification: "Intel Core i5 12th Gen (16 GB/512 GB SSD/Windows 11)",
    Price: 74990,
  },
  {
    Name: "ASUS Vivobook Go",
    Company: "ASUS",
    image: "asus.jpg",
    Specification: "AMD Ryzen 5 Quad Core (8 GB/512 GB SSD/Windows 11)",
    Price: 50990,
  },
  {
    Name: "ASUS ROG Strix G15",
    Company: "ASUS",
    image: "asus.jpg",
    Specification: "AMD Ryzen 7 Octa Core (16 GB/512 GB SSD/Windows 11)",
    Price: 84990,
  },
  {
    Name: "ASUS ROG Zephyrus G14",
    Company: "ASUS",
    image: "asus.jpg",
    Specification: "AMD Ryzen 9 Octa Core (16 GB/1 TB SSD/Windows 11)",
    Price: 129990,
  },
  {
    Name: "MSI Bravo 15",
    Company: "MSI",
    image: "msi.jpg",
    Specification: "AMD Ryzen 5 Hexa Core (8 GB/512 GB SSD/Windows 11)",
    Price: 49999,
  },
  {
    Name: "MSI Modern 14",
    Company: "MSI",
    image: "msi.jpg",
    Specification: "AMD Ryzen 5 Hexa Core (16 GB/512 GB SSD/Windows 11)",
    Price: 48999,
  },
  {
    Name: "MSI GF63 Thin",
    Company: "MSI",
    image: "msi.jpg",
    Specification: "Intel Core i5 12th Gen (16 GB/512 GB SSD/Windows 11)",
    Price: 57999,
  },
  {
    Name: "MSI Katana 15",
    Company: "MSI",
    image: "msi.jpg",
    Specification: "Intel Core i5 13th Gen (16 GB/512 GB SSD/Windows 11)",
    Price: 74999,
  },
  {
    Name: "MSI Katana 17",
    Company: "MSI",
    image: "msi.jpg",
    Specification: "Intel Core i7 12th Gen (16 GB/1 TB SSD/Windows 11)",
    Price: 114999,
  },
  {
    Name: "Lenovo ThinkPad",
    Company: "Lenovo",
    image: "lenovo.jpg",
    Specification: "Intel Core i5 12th Gen (8 GB/512 GB SSD/Windows 11)",
    Price: 40999,
  },
  {
    Name: "Lenovo IdeaPad 3",
    Company: "Lenovo",
    image: "lenovo.jpg",
    Specification: "Intel Core i3 11th Gen (8 GB/256 GB SSD/Windows 11)",
    Price: 35999,
  },
  {
    Name: "Lenovo IdeaPad Slim",
    Company: "Lenovo",
    image: "lenovo.jpg",
    Specification: "Intel Dual Core N4020 (8 GB/256 GB SSD/Windows 11)",
    Price: 43999,
  },
  {
    Name: "Lenovo LOQ",
    Company: "Lenovo",
    image: "lenovo.jpg",
    Specification: "Intel Core i7 13th Gen (16 GB/512 GB SSD/Windows 11)",
    Price: 114990,
  },
  {
    Name: "HP 14s",
    Company: "HP",
    image: "hp.jpg",
    Specification: "Intel Core i3 11th Gen (8 GB/256 GB SSD/Windows 11)",
    Price: 32990,
  },
  {
    Name: "HP Victus",
    Company: "HP",
    image: "hp.jpg",
    Specification: "AMD Ryzen 5 Hexa Core (8 GB/512 GB SSD/Windows 11)",
    Price: 52990,
  },
  {
    Name: "HP Pavilion",
    Company: "HP",
    image: "hp.jpg",
    Specification: "AMD Ryzen 5 Hexa Core (16 GB/512 GB SSD/Windows 11)",
    Price: 32990,
  },
  {
    Name: "Acer One",
    Company: "acer",
    image: "acer.jpg",
    Specification: "Intel Core i3 11th Gen (8 GB/256 GB SSD/Windows 11)",
    Price: 29990,
  },
  {
    Name: "Acer Extensa",
    Company: "acer",
    image: "acer.jpg",
    Specification: "Intel Core i3 11th Gen (8 GB/256 GB SSD/Windows 11)",
    Price: 30990,
  },
  {
    Name: "Acer Aspire 3",
    Company: "acer",
    image: "acer.jpg",
    Specification: "AMD Ryzen 3 Quad Core (16 GB/512 GB SSD/Windows 11)",
    Price: 29990,
  },
  {
    Name: "DELL Vostro",
    Company: "DELL",
    image: "dell.jpg",
    Specification: "Intel Core i3 11th Gen (8 GB/256 GB SSD/Windows 11)",
    Price: 34990,
  },
  {
    Name: "DELL Inspiron",
    Company: "DELL",
    image: "dell.jpg",
    Specification: "Intel Core i3 11th Gen (8 GB/256 GB SSD/Windows 11)",
    Price: 36607,
  },
];
